name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install
      working-directory: ./ # Change if you're using a subdirectory for the project

    - name: Run Tests (Optional)
      run: npm test
      continue-on-error: true

    - name: Build Project (Optional for Static Content)
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Change this if you're using a different directory for built files
